module.exports = {
  builders: 'builders',
  users: 'users',
  customers: 'customers',
  projects: 'projects',
  userProjects: 'user_projects',
  complaints: 'complaints',
  invoices: 'invoices',
  changeOrders: 'change_orders',
  otpSessions: 'otp_sessions',
  files: 'uploads',
  progressUpdates: 'progress_updates',
  estimations: 'estimations',
  feedback: 'feedback',
  notifications: 'notifications',
  tasks: 'tasks',
  approvals: 'approvals',
  schedules: 'schedules',
  delays: 'delays',
  activityLogs: 'activity_logs',
  aiReports: 'ai_reports'
};
